// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/generate-test.ts";
import * as $1 from "./routes/api/get-answers.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Test.tsx";

const manifest = {
  routes: {
    "./routes/api/generate-test.ts": $0,
    "./routes/api/get-answers.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Test.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
